# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - name: Set up git
      uses: actions/checkout@v2

    # https://github.com/actions/setup-java
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # https://github.com/actions/cache
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          .gradle
          build
          app/backend/build
          app/backend-api/build
          app/backend-hsql/build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    # https://github.com/gradle/gradle
    - name: Build with Gradle
      env:
        JAVA_OPTS: '-Dorg.gradle.daemon=false'
        GRADLE_USER_HOME: .gradle
      run: chmod +x gradlew && ./gradlew build asciidoctor jacocoTestReport

    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy preview
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir:  pages
